# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Gradebook | Proyecto de Software 2010
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [/sfPropelPlugin/css/global.css, main.css]

  javascripts:    [jquery-1.4.4.min.js]

  has_layout:     true
  layout:         layout
