<?php


/**
 * Skeleton subclass for representing a row from the 'gb_grade' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov 16 21:33:31 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Grade extends BaseGrade {

} // Grade
