connection: propel

classes:
  Grade:
    tableName: gb_grade
    columns:
      id:
      student_id:
        type: integer
        foreignClass: Student
        foreignReference: id
        onDelete: cascade
        required: true
      grade:
        type: float
        required: true
      comments:
        type: longvarchar
      created_at:
        type: date

  Group:
    tableName: gb_group
    columns:
      id:
      number:
        type: integer
        required: true
        unique: true

  Student:
    tableName: gb_student
    columns:
      id:
      first_name:
        type: varchar(200)
        required: true
      last_name:
        type: varchar(200)
        required: true
      number:
        type: varchar(15)
      group_id:
        type: integer
        foreignClass: Group
        foreignReference: id
        onDelete: setnull
